version: '3.7'

services:
    app-microservice:
        build:
            context: ./app-microservice
        image: app-microservice
        restart: unless-stopped
        expose:
            - "8080"
        deploy:
            replicas: 3


    nginx-balancer:
        image: nginx
        container_name: nginx-balancer
        restart: unless-stopped
        volumes:
            - ./nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app-microservice
        ports:
            - "8080:4000"


    nginx-html:
        image: nginx
        container_name: nginx-html
        restart: unless-stopped
        volumes:
            - ./html:/usr/share/nginx/html:ro
        depends_on:
            - nginx-balancer
        ports:
            - "4000:8080"
